name: m2-tenant-app
region: sfo
features:
  - buildpack-stack=ubuntu-22

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

static_sites:
  - name: m2-tenant-app
    environment_slug: node-js
    source_dir: /
    github:
      repo: nalancer08/m2-tenant-app
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${VITE_API_URL}
      - key: VITE_TENANT_APP_URL
        scope: BUILD_TIME
        value: ${VITE_TENANT_APP_URL}
      - key: VITE_GOOGLE_PLACES_KEY
        scope: BUILD_TIME
        value: ${VITE_GOOGLE_PLACES_KEY}

ingress:
  rules:
    - component:
        name: m2-tenant-app
      match:
        path:
          prefix: /
