name: m2-tenant-app
region: sfo

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

ingress:
  rules:
    - component:
        name: m2-tenant-app
      match:
        path:
          prefix: /

services:
  - name: m2-tenant-app
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: nalancer08/m2-tenant-app
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    health_check:
      http_path: /
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${VITE_API_URL}
      - key: VITE_TENANT_APP_URL
        scope: BUILD_TIME
        value: ${VITE_TENANT_APP_URL}
      - key: VITE_GOOGLE_PLACES_KEY
        scope: BUILD_TIME
        value: ${VITE_GOOGLE_PLACES_KEY}
