import { Link, useParams } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { Card } from '../../components/primitives/Card';
import { Button } from '../../components/primitives/Button';
import { Logo } from '../../components/primitives/Logo';
import { IconCheck, IconClock, IconShield } from '../../components/icons';
import { publicDealApi } from '../../api/public-deal';
import { formatCents, formatPropertyAddress } from '../../lib/format';
import styles from './LinkLandingPage.module.css';

// Tokens generated by the API are 6-char alphanumeric (uppercase + digits,
// no ambiguous chars like 0/O/I/1). Anything else hitting /:something is
// not a token — render the "not found" state instead of bothering the API.
const TOKEN_PATTERN = /^[A-Z0-9]{6,12}$/i;

export function LinkLandingPage() {
  const { linkToken = '' } = useParams<{ linkToken: string }>();
  const isPlausibleToken = TOKEN_PATTERN.test(linkToken);

  const q = useQuery({
    queryKey: ['public-deal', linkToken],
    queryFn: () => publicDealApi.get(linkToken),
    retry: false,
    enabled: isPlausibleToken,
  });

  if (!isPlausibleToken) {
    return <NotFoundShell />;
  }

  if (q.isLoading) {
    return (
      <div className={styles.root}>
        <Header />
        <div className={styles.body}>
          <p className={styles.subtitle}>Cargando tu invitación…</p>
        </div>
      </div>
    );
  }

  if (q.error || !q.data) {
    return <NotFoundShell />;
  }

  const { deal, property, line_items, total_cents, broker } = q.data;
  const brokerName = broker
    ? `${broker.first_name} ${broker.last_name}`.trim()
    : 'tu asesor';
  const brokerFirst = broker?.first_name?.trim() || 'tu asesor';
  const principalFirst = deal.principal_tenant_name?.trim().split(' ')[0] ?? null;

  if (deal.status === 'cancelled') {
    return (
      <div className={styles.root}>
        <Header folio={deal.folio} />
        <div className={styles.body}>
          <span className={styles.eyebrow}>Invitación cancelada</span>
          <h1 className={styles.title}>
            Esta investigación ya no <em>está activa</em>.
          </h1>
          <p className={styles.subtitle}>
            {brokerName} canceló esta invitación. Si la sigues necesitando,
            pídele al asesor que te genere una nueva liga.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.root}>
      <Header folio={deal.folio} />

      <div className={styles.body}>
        <span className={styles.eyebrow}>
          <span className={styles.eyebrowDot} aria-hidden /> Investigación de arrendamiento
        </span>
        <h1 className={styles.title}>
          Hola{principalFirst ? <> <em>{principalFirst}</em></> : ''},
          <br />
          {brokerFirst} te invita a <em>Metro Cuadrado</em>.
        </h1>
        <p className={styles.subtitle}>
          Completa tu información en unos minutos y obtén tu resultado de
          investigación en aproximadamente 24 horas.
        </p>

        {property ? (
          <Card>
            <span className={styles.cardLabel}>Propiedad</span>
            <p className={styles.cardMain}>{formatPropertyAddress(property)}</p>
            <p className={styles.cardMeta}>
              {[property.neighborhood, property.municipality].filter(Boolean).join(' · ')}
            </p>
            <p className={styles.cardMeta}>
              {property.city} · {property.state} · CP {property.postal_code}
            </p>
            {deal.rent_amount_cents ? (
              <p className={styles.cardPrice}>
                {formatCents(deal.rent_amount_cents, deal.currency)} <span className={styles.cardPriceSub}>/ mes</span>
              </p>
            ) : null}
          </Card>
        ) : null}

        {line_items.length > 0 ? (
          <Card>
            <span className={styles.cardLabel}>Qué incluye</span>
            <ul className={styles.includes}>
              {line_items.map((li) => (
                <li key={li.id} className={styles.includesRow}>
                  <span className={styles.includesIcon}><IconCheck width={14} height={14} /></span>
                  <span className={styles.includesText}>
                    {li.product?.name ?? 'Producto'}
                    {li.product?.description ? (
                      <span className={styles.includesDesc}> · {li.product.description}</span>
                    ) : null}
                  </span>
                </li>
              ))}
            </ul>
            <p className={styles.cardPrice}>
              {formatCents(total_cents, deal.currency)} <span className={styles.cardPriceSub}>total</span>
            </p>
          </Card>
        ) : null}

        <Card>
          <div className={styles.trustRow}>
            <span className={styles.trustIcon}><IconShield /></span>
            <span>Tus datos se comparten <strong>solo</strong> con {brokerName}.</span>
          </div>
          <div className={styles.trustRow}>
            <span className={styles.trustIcon}><IconClock /></span>
            <span>Resultado promedio en 24 horas desde que terminas y pagas.</span>
          </div>
        </Card>

        <div className={styles.actions}>
          <Link to={`/auth/signup?link_token=${encodeURIComponent(linkToken)}`} style={{ display: 'block' }}>
            <Button fullWidth size="lg">Crear cuenta y continuar</Button>
          </Link>
          <Link to={`/auth/login?link_token=${encodeURIComponent(linkToken)}`} style={{ display: 'block' }}>
            <Button fullWidth size="lg" variant="ghost">Ya tengo cuenta</Button>
          </Link>
        </div>

        <p className={styles.legalFootnote}>
          Al continuar deberás aceptar nuestro Aviso de Privacidad, el Tratamiento
          de Datos Personales Sensibles y los Términos y Condiciones.
        </p>
      </div>
    </div>
  );
}

function Header({ folio }: { folio?: string } = {}) {
  return (
    <header className={styles.header}>
      <div className={styles.headerBrand}>
        <Logo size={28} />
        <span className={styles.headerBrandName}>Metro Cuadrado</span>
      </div>
      {folio ? <span className={styles.folio}>{folio}</span> : null}
    </header>
  );
}

function NotFoundShell() {
  return (
    <div className={styles.root}>
      <Header />
      <div className={styles.body}>
        <span className={styles.eyebrow}>Link no encontrado</span>
        <h1 className={styles.title}>
          Esta liga <em>ya no está disponible</em>.
        </h1>
        <p className={styles.subtitle}>
          El enlace pudo haber expirado o ser incorrecto. Contacta a tu asesor
          para que te comparta uno nuevo.
        </p>
      </div>
    </div>
  );
}
